//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11 {
            get {
                object obj = ResourceManager.GetObject("11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _274862_nightwing_by_vookasheen_on_deviantart_4896x3421_h {
            get {
                object obj = ResourceManager.GetObject("274862_nightwing-by-vookasheen-on-deviantart_4896x3421_h", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5a350088a39ab0_8666733715134229846701 {
            get {
                object obj = ResourceManager.GetObject("5a350088a39ab0.8666733715134229846701", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5a350088a39ab01 {
            get {
                object obj = ResourceManager.GetObject("5a350088a39ab01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_arrow_computer_icons_circle_5adb9e2f1a2f56_9570193715243423191073 {
            get {
                object obj = ResourceManager.GetObject("kisspng-arrow-computer-icons-circle-5adb9e2f1a2f56.9570193715243423191073", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_clip_art_delete_image_icon_5b45dc96d93802_2391582815313051108897 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-clip-art-delete-image-icon-5b45dc96d93802.2391582815313051" +
                        "108897", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_download_back_icon_5b2093476ffac8_6639606615288615114587 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-download-back-icon-5b2093476ffac8.6639606615288615114587", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_login_icon_design_5b2c21206296c8_1035883515296187204038 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-login-icon-design-5b2c21206296c8.1035883515296187204038", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_receipt_icon_design_cartoon_line_5adbbb02f30ec4_6745629815243496989956 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-receipt-icon-design-cartoon-line-5adbbb02f30ec4.6745629815" +
                        "243496989956", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_user_person_clip_art_people_icon_5abe2b27117a62_6814763815224123270716 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-user-person-clip-art-people-icon-5abe2b27117a62.6814763815" +
                        "224123270716", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_user_person_clip_art_people_icon_5abe2b27117a621 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-user-person-clip-art-people-icon-5abe2b27117a621", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_database_computer_icons_clip_art_5b21704ddbfc20_3210073115289180939011 {
            get {
                object obj = ResourceManager.GetObject("kisspng-database-computer-icons-clip-art-5b21704ddbfc20.3210073115289180939011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_door_computer_icons_lock_key_exit_5aca61f9300381_1306238215232127931967 {
            get {
                object obj = ResourceManager.GetObject("kisspng-door-computer-icons-lock-key-exit-5aca61f9300381.1306238215232127931967", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_gear_logo_gear_icon_5b25208fd6bd69_4549555015291598238796 {
            get {
                object obj = ResourceManager.GetObject("kisspng-gear-logo-gear-icon-5b25208fd6bd69.4549555015291598238796", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_login_computer_icons_iconfinder_website_login_key_icon_lock_locked_login_5ab05c9633fe41_621215531521507478213__1_ {
            get {
                object obj = ResourceManager.GetObject("kisspng-login-computer-icons-iconfinder-website-login-key-icon-lock-locked-login-" +
                        "5ab05c9633fe41.621215531521507478213 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_payment_computer_icons_money_pay_per_click_cheque_telesales_5b2f6c8fd3ed15_0471515815298346398681 {
            get {
                object obj = ResourceManager.GetObject("kisspng-payment-computer-icons-money-pay-per-click-cheque-telesales-5b2f6c8fd3ed1" +
                        "5.0471515815298346398681", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_plus_and_minus_signs_computer_icons_symbol_plus_5abe3ddf6ca553_641603711522417119445 {
            get {
                object obj = ResourceManager.GetObject("kisspng-plus-and-minus-signs-computer-icons-symbol-plus-5abe3ddf6ca553.6416037115" +
                        "22417119445", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_3 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
